### PR TITLE
Syntax Rewrite for v0.12.x

### LINKED ISSUE #1: Add support for tfvars+tfstate
I haven't looked at the tmLanguage specification, but it would be nice to define some kind of mapping for the following:
- `*.tfvars` => `*.ini` (there may be some small differences in escaping, but I'd just ignore that for any first implementation)
- `*.tfstate` => `*.json`

btw. thanks again for the effort invested into this! :+1:

### LINKED ISSUE #31: new terraform block isn't highlighted
[The new `terraform` block](https://www.terraform.io/docs/configuration/terraform.html) isn't highlighted.

terraform_block

Also, notice that the `>=` in the version constraint isn't highlighted correctly.

### LINKED ISSUE #34: Unit testing
Would be great to get some unit tests - see:

- https://www.sublimetext.com/docs/3/syntax.html#testing
- https://github.com/SublimeText/UnitTesting

### PR DESCRIPTION
**Pull request by patrickrgaffney**
## HCL2

Since [v0.12](https://github.com/hashicorp/terraform/releases/tag/v0.12.0), the underlying [HCL](https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/spec.md) syntax has undergone a lot of changes. This PR reworks the sublime-syntax to better support the new language features.

## Rationale

I've only been updating the `.sublime-syntax` file — as I only use Sublime. A quick Google search shows a few different converter tools to turn it back into a PList-style `.tmLanguage` file if that's still desired.

While reworking the syntax I've been trying to update the scopes to match the [official conventions](https://www.sublimetext.com/docs/3/scope_naming.html) better (if possible). All of the changes made so far can be seen in the `changes.md` file. I can remove that file when this is complete — I've been trying to keep a thorough list there.

The major goal of this PR was to update the syntax for the new HCL2 syntax. In addition to Terraform, other Hashicorp projects are using HCL for configuation now: Vault, Nomad, (and soon 🤞) Packer. The changes in this PR should better support non-Terraform-specific HCL files going forward.

I added a lot of documentation to the `sublime-syntax` and re-ordered it to better follow the HCL spec. I also added fairly extensive unit testing. 🎉 

Merging this PR would close the following open issues:

- Closes #1 
- Closes #31 
- Closes #34

## Progress / TODO

- [x] Comments
    - [x] inline `#`
    - [x] inline `//`
    - [x] inline `/* ... */`
    - [x] block `/* ... */`
- [x] Language Constants
    - [x] `true` / `false`
    - [x] `null`
- [x] Numeric Constants
    - [x] integers
    - [x] floating-point
    - [x] exponents
    - [x] signed exponents
- [x] Strings
    - [x] double quotes: `string.quoted.double.terraform`
    - [x] punctuation scopes
    - [x] character escapes
    - [x] string interpolation
        - [x] `${}`
        - [x] `%{}`
        - [x] left-trim and right-trim `~`
        - [x] include operators
        - [x] include attributes
        - [x] include builtin variables
        - [x] include functions
        - [x] include builtin functions
        - [x] include objects
        - [x] include tuples
        - [x] `if` directives
        - [x] `for` directives
    - [x] heredocs
        - [x] `<<` and `<<-` operators
        - [x] allow multiline
        - [x] allow identifier before first newline
        - [x] allow identifier on last line
- [x] Operators
    - [x] comparison
    - [x] arithmetic
    - [x] logic
    - [x] conditional
    - [x] ellipsis `...`
    - [x] parenthesis
    - [x] splat operators `.*` and `[*]`
    - [x] `:` in for-expressions
    - [x] `=>` in for-expressions
- [x] Attribute-Access
    - [x] identifiers
    - [x] definitions
    - [x] dot-access
    - [x] match subscripts
- [x] Tuples
    - [x] match bracket `[]` syntax
    - [x] include literals
    - [x] match over multi-line
    - [x] include comments
    - [x] include operators
    - [x] include attribute-access
    - [x] allow nested tuples
    - [x] match comma `,`
    - [x] include built-in variables
    - [x] include objects
    - [x] include function calls
    - [x] `for` expressions
- [x] Objects
    - [x] match curly `{}` syntax
    - [x] include literals
    - [x] match over multi-line
    - [x] include comments
    - [x] include operators
    - [x] include tuples
    - [x] include function calls
    - [x] allow nested objects
    - [x] attribute definition
    - [x] attribute access
    - [x] strings as keys
    - [x] `for` expressions
    - [x] include built-in variables
    - [x] computed attribute names `()`
- [x] Functions
    - [x] match identifier function name
    - [x] match named parameter values
    - [x] include literals in parameter list
    - [x] include tuples in parameter list
    - [x] include objects in parameter list
    - [x] include operators in parameter list
    - [x] match comma `,`
    - [x] allow nested function calls
    - [x] include comments
    - [x] include built-in variables
    - [x] `for` expressions
    - [x] allow over multiple lines
    - [x] meta: `meta.function`
- [x] `for` Expressions
    - [x] match inside tuple
    - [x] match inside object
    - [x] `for` keyword
    - [x] `if` keyword
    - [x] `in` keyword
    - [x] `:` operator
    - [x] `=>` operator
    - [x] include literals
    - [x] include operators
    - [x] include function calls
    - [x] include brackets
    - [x] include builtin variables
    - [x] include attribute-access
    - [x] allow over multiple lines
    - [x] include comments
- [x] Blocks
    - [x] match type
    - [x] match optional number of string labels
    - [x] match optional number of identifier labels
    - [x] meta_scope for entire block
    - [x] allow nested blocks
    - [x] include operators
    - [x] include literals
    - [x] include functions
    - [x] include objects
    - [x] include tuples
    - [x] include attribute access
    - [x] include builtin variables
    - [x] include builtin block-types
    - [x] include attribute definition
    - [x] include constants
    - [x] allow multi-line
    - [x] include comments
    - [x] meta: `meta.block`
- [x] Terraform specific
    - [x] built-in functions (as of v0.12.8)
    - [x] built-in variables
    - [x] built-in block types
    - [x] built-in primitive types (`string`,  `number`, `bool`, `any`)
    - [x] `import` statements

### CODE REVIEW

**Comment by alexlouden** [comment]
This looks amazing, thank you so much! I've [invited](https://github.com/alexlouden/Terraform.tmLanguage/invitations) you to be a contributor, if you'd like? 😃 

One note on the `.tmLanguage` file - this repo's included as a submodule by linguist, Github's code syntax highlighting library for github.com (see [my PR here](https://github.com/github/linguist/pull/3392)). [It says](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting) they use "textMate-compatible grammars", which I'm guessing means the PList style. So when you're ready to release it we can run a script to convert the `.sublime-syntax` back to `tmLanguage`, and all your improvements will eventually go live across github.com too!

**Comment by patrickrgaffney** [comment]
That's awesome, thanks!

I'll take another look at back-filling the `.tmLanguage` file when I'm finished with the improvements. I didn't realize GH was using this package — that's really cool.

**Comment by patrickrgaffney** [comment]
Okay, so the feature list of [v0.12](https://github.com/hashicorp/terraform/releases/tag/v0.12.0) is complete. 🎉 

All listed changes now have tests as well. I've been dogfooding this branch at home/work over the past couple of weeks, and I'm pretty happy with the results.

IMO this can also close #1, as we support `*.tfvars` in this syntax's `file_extensions` — those files basically [use the same syntax](https://www.terraform.io/docs/configuration/variables.html#variable-definitions-tfvars-files). I've also made a [PR on the Packages repo](https://github.com/sublimehq/Packages/pull/2095) to add `*.tfstate` files to the list of valid JSON `file_extensions`.

I was thinking about making a `CHANGELOG.md` file in the root — a la [KeepAChangelog](https://keepachangelog.com/en/1.0.0/) — with a nicely formatted list of the changes currently in `changes.md`. What do you think of that approach? It could be backfilled with all the [previously released versions](https://github.com/alexlouden/Terraform.tmLanguage/releases).

Finally, regarding the GitHub Linguist support, you were right that they don't support the [.sublime-syntax](https://github.com/github/linguist/issues/3209) grammers. It's somewhat complicated to back-fill the .tmLanguage file, as the sublime-syntax format is a superset of what the TextMate grammers offered, therefore there's no automated/programmatic way to convert from .sublime-syntax to .tmLanguage.

I'm willing to spend some time going through the .YAML-tmLanguage file and moving some of the new regular expressions over if we decide that's the best path forward. I don't really see a lot of other options — and while that wouldn't cover the _all_ of the enhancements made on this PR, it would get that grammar closer to where we're at today with the v0.12 syntax. Thoughts?

**Comment by jeffbyrnes** [comment]
Very fond of a changelog, 👍 to that.

I’d say that a “best effort” `tmLanguage` for the GitHub Linguist support is reasonable.

**Comment by patrickrgaffney** [comment]
Added a new [CHANGELOG](https://github.com/alexlouden/Terraform.tmLanguage/blob/64e3e20239f972cdaeef6500c4df7b51eaef295d/CHANGELOG.md) file to the root of the project. I formatted all the changes on this PR in the `Unreleased` section and removed the old `changes.md` file. I back-filled all the previous releases in the new file.

**Comment by ccpost** [comment]
Just wanted to drop in and say thanks so much for this! I've been running this PR branch in Sublime for the past couple days while doing a huge migration to 0.12 and it's been a total game-changer. 🙌

**Comment by patrickrgaffney** [comment]
Added a `JSON (Terraform)` syntax for *.tfstate files — [per @deathaxe's suggestion](https://github.com/sublimehq/Packages/pull/2095#issuecomment-533807072).

**Comment by patrickrgaffney** [comment]
I started moving the new matches/scopes from the `sublime-syntax` to the `tmLanguage` definition today. It's been fairly painless so far — biggest thing I've had to drop is the `clear_scopes` directive inside string interpolation. I set up a new `syntax_test_terraform_tm.tf` file to test the `tmLanguage` definition independent of the `sublime-syntax`. I'll set up another TODO list below for that definition:

## `tmLanguage` Progress

- [x] comments
- [x] language constants
- [x] numeric constants
- [x] strings
- [x] string interpolation
- [ ] heredocs
- [x] operators
- [ ] attribute-access
- [x] tuples
- [ ] objects
- [ ] functions
- [ ] `for` expressions
- [ ] blocks
- [ ] built-in functions
- [ ] built-in variables
- [ ] built-in block types
- [ ] built-in primitive types
- [ ] `import` statements

**Comment by patrickrgaffney** [comment]
I've finished updating the `.tmLanguage` file. It matches very closely with the `.sublime-syntax` now. The only major difference is the combination of block and object (maps) bodies. Without the stack-based regex system of the Sublime syntax, it was too hard to differentiate between a block body and a map. There are tests for both files, and they use the same inputs — the only differences being the slightly different scope names in a few circumstances.

[According to the `linguist` contributing notes](https://github.com/github/linguist/blob/master/CONTRIBUTING.md#fixing-syntax-highlighting), it seems this will get picked up once it's merged and they cut a new release. I've included some examples below of what it will look like once updated below — the post-merge examples are rendered using Lightroom and the `.tmLanguage` file on this PR:

- expressions: [Currently](https://github.com/hashicorp/terraform-guides/blob/master/infrastructure-as-code/terraform-0.12-examples/first-class-expressions/main.tf), [After this update](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=yaml&grammar_url=https%3A%2F%2Fgithub.com%2Falexlouden%2FTerraform.tmLanguage%2Fblob%2F78864d9680c297a7ab84b0977141ad6e056868c9%2FTerraform.YAML-tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fhashicorp%2Fterraform-guides%2Fblob%2Fmaster%2Finfrastructure-as-code%2Fterraform-0.12-examples%2Ffirst-class-expressions%2Fmain.tf&code=).
- `for` expressions: [Currently](https://github.com/hashicorp/terraform-guides/blob/master/infrastructure-as-code/terraform-0.12-examples/for-each-for-resources/main.tf), [After this update](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=yaml&grammar_url=https%3A%2F%2Fgithub.com%2Falexlouden%2FTerraform.tmLanguage%2Fblob%2F78864d9680c297a7ab84b0977141ad6e056868c9%2FTerraform.YAML-tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fhashicorp%2Fterraform-guides%2Fblob%2Fmaster%2Finfrastructure-as-code%2Fterraform-0.12-examples%2Ffor-each-for-resources%2Fmain.tf&code=)
- String templates: [Currently](https://github.com/hashicorp/terraform-guides/blob/master/infrastructure-as-code/terraform-0.12-examples/new-template-syntax/main.tf), [After this update](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=yaml&grammar_url=https%3A%2F%2Fgithub.com%2Falexlouden%2FTerraform.tmLanguage%2Fblob%2F78864d9680c297a7ab84b0977141ad6e056868c9%2FTerraform.YAML-tmLanguage&grammar_text=&code_source=from-url&code_url=https%3A%2F%2Fgithub.com%2Fhashicorp%2Fterraform-guides%2Fblob%2Fmaster%2Finfrastructure-as-code%2Fterraform-0.12-examples%2Fnew-template-syntax%2Fmain.tf&code=)

I consider this PR to be complete. The CHANGELOG is up-to-date, all the changes are in the `Unreleased` section for now. @alexlouden let me know if you have any additional comments/concerns.

**Comment by alexlouden** [comment]
Hi @patrickrgaffney - firstly, well done - this looks amazing! 

I've cloned your branch and had a look through a few of my projects, and I think I've found a couple of bugs - see [lightshow](https://github-lightshow.herokuapp.com/?utf8=%E2%9C%93&scope=from-url&grammar_format=yaml&grammar_url=https%3A%2F%2Fraw.githubusercontent.com%2Fpatrickrgaffney%2FTerraform.tmLanguage%2Frewrite%2FTerraform.YAML-tmLanguage&grammar_text=&code_source=from-text&code_url=https%3A%2F%2Fgithub.com%2Fhashicorp%2Fterraform-guides%2Fblob%2Fmaster%2Finfrastructure-as-code%2Fterraform-0.12-examples%2Ffirst-class-expressions%2Fmain.tf&code=%23+DNS+for+subdomain%0D%0Aresource+%22aws_route53_record%22+%22my-ns%22+%7B%0D%0A++zone_id+%3D+%22%24%7Baws_route53_zone.main.zone_id%7D%22%0D%0A++name++++%3D+%22mydomain.com%22%0D%0A++type++++%3D+%22NS%22%0D%0A++ttl+++++%3D+%22300%22%0D%0A%0D%0A++records+%3D+%5B%0D%0A++++%22%24%7Baws_route53_zone.project.name_servers.0%7D%22%2C%0D%0A++++%22%24%7Baws_route53_zone.project.name_servers.1%7D%22%2C%0D%0A++++%22%24%7Baws_route53_zone.project.name_servers.2%7D%22%2C%0D%0A++++%22%24%7Baws_route53_zone.project.name_servers.3%7D%22%2C%0D%0A++%5D%0D%0A%0D%0A++lifecycle+%7B%0D%0A++++%23+ignore_changes+%3D+%5B%22records%22%5D%0D%0A++%7D%0D%0A%7D%0D%0A%0D%0A%23+this+is+a+comment%2C+but+it%27s+getting+recognised+as+a+string)

- it's recognising numbers in variables as constants
- `punctuation.definition.string.end` isn't getting recognised
- any code after the block seem to be getting recognised as a string
- the number at the end of `xxx.name_servers.0` isn't getting highlighted

Screen Shot 2019-10-10 at 11 06 14 am

Screen Shot 2019-10-10 at 11 05 46 am

Current highlighting:
image


```terraform
# DNS for subdomain
resource "aws_route53_record" "my-ns" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  name    = "mydomain.com"
  type    = "NS"
  ttl     = "300"

  records = [
    "${aws_route53_zone.project.name_servers.0}",
    "${aws_route53_zone.project.name_servers.1}",
    "${aws_route53_zone.project.name_servers.2}",
    "${aws_route53_zone.project.name_servers.3}",
  ]

  lifecycle {
    # ignore_changes = ["records"]
  }
}

# this is a comment, but it's getting recognised as a string
```

As a side note, it looks like the `.` in interpolation strings isn't getting recognised as `keyword.control.period.terraform` any more. I thought this was kind of nice, helped visually split up long string interpolation statements - what do you think?

**Comment by alexlouden** [comment]
I asked a friend to test it too, and he had the following feedback:

1. Should the env vars here be HEREDOC red?
image

```terraform
resource "aws_lambda_function" "slack_notify_lambda" {
  
  environment {
    variables = {
      SLACK_CHANNEL = "${var.slack_alert_channel}"
      HOOK_URL = "${var.slack_alert_web_hook}"
    }
  }
}
```

2. `aws_kms_key` is colored orange, but not `aws_db_instance`

Screen Shot 2019-10-10 at 11 54 03 am


```terraform
resource "aws_iam_policy" "policy" {
  name        = "test_policy"
  path        = "/"
  description = "My test policy"

  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "ec2:Describe*"
      ],
      "Effect": "Allow",
      "Resource": "${aws_db_instance.db.arn}"
    },
    {
      "Action": [
        "ec2:DummyExample*"
      ],
      "Effect": "Allow",
      "Resource": "${jsonencode(aws_db_instance.db.arn}}"
    }
  ]
}
EOF
}
```

3. I don’t know if I necessarily agree that functions and the start of some namespaces should be colored the same

4. I could use more color to really help see the structure here, the string interpolations are all white. (Maybe highlighting the periods red again would help here?)

image

```terraform
resource "aws_iam_policy_attachment" "test-attach" {
  name       = "test-attachment"
  users      = ["${aws_iam_user.user.name}"]
  roles      = [
    "${aws_iam_role.role1.name}",
    "${aws_iam_role.role2.name}",
    "${aws_iam_role.role3.name}",
    "${aws_iam_role.role4.name}",
  ]
  groups     = ["${aws_iam_group.group.name}"]
  policy_arn = "${aws_iam_policy.policy.arn}"
}
```

**Comment by alexlouden** [comment]
So nothing major, but I thought I'd pass it on!

What do you think about highlighting string interpolation the same as JS does? I think this would help it stand out a bit more, and make it a bit clearer when there's a missing a trailing curly bracket.

image

The `${` is `keyword.other.substitution.begin` and the period is `keyword.operator.accessor`

**Comment by alexlouden** [comment]
For anyone else interested who'd like to test it, you can clone the branch like so:

```bash
cd ~/Library/Application Support/Sublime Text 3/Packages/
git clone https://github.com/patrickrgaffney/Terraform.tmLanguage.git -b rewrite NewTerraform
```

then in `NewTerraform/Terraform.sublime-syntax` if you change it to `name: Terraform2` it'll show up as a separate syntax

**Comment by patrickrgaffney** [comment]
Ahh, a couple of goofs. 😅  I made some fixes/comments:

- The `.` is still being matched, but as `punctuation.accessor.dot` now. This matches the [scope naming conventions](https://www.sublimetext.com/docs/3/scope_naming.html#punctuation). I'm cool with changing this to be something else though.
- Most of the issues in the `aws_route53_record.my-ns` example were related to not matching on integer variable members. It wasn't popping the scope off that first attribute-access, and it was borking the rest of that file.
- The environment variables are key's in the `variables` map. They're getting `entity.name.tag`. I think a lot of different color schemes highlight `entity.` differently ([at least according to the docs](https://www.sublimetext.com/docs/3/scope_naming.html#color_schemes)). I'm good with changing this one as well if you had something else in mind.
- `aws_kms_key` is a parameter in that function, and it's getting [`variable.parameter`](https://www.sublimetext.com/docs/3/scope_naming.html#variable). `aws_db_instance` is a free identifier, which aren't being highlighted. There were a lot of false positives being picked up when I tried matching identifiers outside of a more specific scope. All attributes in attribute-access (i.e. `thing` in `some.thing`) are scoped as `variable.other.member` from the docs.
- Function names are scoped as `variable.function` per the naming convertions. *Known* resource blocks are scoped as `storage.type` (that was what we had before IIRC), and *unknown* resource blocks are scoped as `entity.name.type`.
- String interpolation operators are scoped as `punctuation.section.interpolation.[begin|end]` with `meta.interpolation` as the `meta_scope`. I think I stole those from the standard Golang package. I'm cool with changing it to follow what's in the JS package.
- The `iam_policy` example looks like it's missing a `)` to close the `jsonencode()` function call parameter list, which is making the rest of the file's scopes break.

I pushed up fixes for the integers in the identifier and the integer member names in attribute-access. Let me know if you run into anything else. All the scope names were lifted from the naming conventions page or other standard packages. I'm good with changing any of them to better reflect meaning/scope or better support color schemes. I tend to exclusively use my own personal color scheme so I kind of live in a bubble. 😄

**Comment by alexlouden** [comment]
Thanks for your reply and all the details! And thank you for fixing the above bug, I'm so impressed with all your tests - that's something I've wanted to add for ages!

> The . is still being matched, but as punctuation.accessor.dot now. This matches the scope naming conventions. I'm cool with changing this to be something else though.  

> String interpolation operators are scoped as punctuation.section.interpolation.[begin|end] with meta.interpolation as the meta_scope. I think I stole those from the standard Golang package. I'm cool with changing it to follow what's in the JS package.

Yeah if you're okay with changing both of these to match JS then I think that would add a bit of clarity in common colour schemes? I'm definitely not an expert at this so I don't know what the best option is!

> The iam_policy example

Whoops - my mistake! I wonder whether we could do something like JS does with `invalid.illegal.newline.js`?

image

> aws_kms_key is a parameter in that function, and it's getting `variable.parameter`.

Maybe it looks strange because only `x` in `${jsonencode(x.y.z)}` gets the `variable.parameter` scope? In Python (and JS) that scope seems to be used in the function parameter definitions, not when the function is called:

image

> The environment variables are key's in the variables map. They're getting `entity.name.tag`

Ah yeah it does seem to be pretty varied - in JS object keys get `constant.other.object.key.js`, Python they get `meta.mapping.key.python` and then the type of the key, e.g. `string.quoted.single.python`. What do you reckon?

**Comment by alexlouden** [comment]
Oh just a thought - I think we should check that bugs that people have reported and have since been fixed are still fixed in the new version, e.g. #28, #26, #23, #21, #18

**Comment by patrickrgaffney** [comment]
Okay, just pushed up some changes:

- Changed attribute-access by `.` scope [to match JS](https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax#L1707-L1727).
- From what I can tell, it appears we are matching string interpolation punctuation [the same as JS](https://github.com/sublimehq/Packages/blob/master/JavaScript/JavaScript.sublime-syntax#L950-L970) — via `punctuation.section.interpolation.[begin|end]` plus the `meta.interpolation` scope. This could be different depending on which version of Sublime you're on. I'm running Build 3210 from the Dev channel.
- I'm cool with adding some `illegal` scopes to the definitions. Maybe they could come in a separate PR? I can create an issue to track it if that works for you.
- I agree with you on the parameter highlighting. Looking through other standard language packages it looks like they only match parameter names on definition and for named parameters. Since HCL currently doesn't allow you provide named parameters or define your own functions, I removed the `variable.parameter` matching.

Object keys seem to be a bit of a mixed bag, here's what some of the standard languages do:
    - JS: `meta.object-literal.key.js`
    - Python: for dictionaries, keys are quoted, and thus are highlighted as strings with `meta.mapping.key.python`.
    - Go: for maps, keys can be any type that is [comparable](https://golang.org/ref/spec#Comparison_operators) — which is quite a few of them. They're highlighted as a literal of that type, without a `meta_scope`.

We're currently using `entity.name.tag`, which is part of the ["minimal color scheme coverage"](https://www.sublimetext.com/docs/3/scope_naming.html#color_schemes) in the Sublime docs. I left it as that for now as I didn't have a better idea, but I'm open to other suggestions.

I went through and added additional tests to cover the issues in #28, #26, #21, and #18. The tests we're already covering #23.

**Comment by patrickrgaffney** [comment]
I did some more digging into the object key syntax scopes today. It seems like most of the [official sublime-syntaxes](https://github.com/sublimehq/Packages) use a meta scope of `meta.mapping.key` on the entire key along with `string.unquoted` or `string.quoted`. Seems like this will be the standard way forward per [this RFC](https://github.com/sublimehq/Packages/issues/421).

Found in the [following syntaxes](https://github.com/sublimehq/Packages/search?q=%22meta.mapping.key%22&unscoped_q=%22meta.mapping.key%22): JS, Git Config, Lua, Python, Erlang, JSON.

I'm good with updating this package to use that scope, sound good @alexlouden?

**Comment by alexlouden** [comment]
> I'm good with updating this package to use that scope, sound good @alexlouden?

Perfect, thank you!

> From what I can tell, it appears we are matching string interpolation punctuation the same as JS — via punctuation.section.interpolation.[begin|end] plus the meta.interpolation scope.

Ah sorry, my [previous comment](https://github.com/alexlouden/Terraform.tmLanguage/pull/39#issuecomment-540341905) was using [babel-sublime](https://github.com/babel/babel-sublime) (imo big improvement over the built-in JS one), which uses `keyword`:

> image
> 
> The `${` is `keyword.other.substitution.begin` and the period is `keyword.operator.accessor`

if I just use the JS plugin then it doesn't highlight the `${` or the period at all (just white). Are you okay with using these?

**Comment by alexlouden** [comment]
Also again - thank you so much for doing all this!

**Comment by alexlouden** [comment]
I've just set up CircleCI to unit test the repo, failing at the moment since there aren't any tests but maybe will test this PR next commit?

**Comment by patrickrgaffney** [comment]
Interesting. I used to use `babel-sublime` pretty much exclusively, but recently the builtin-in JS package has gotten a lot better — any version [after v3.1](https://www.sublimetext.com/blog/articles/sublime-text-3-point-1) has most of the newer TC-39 features. 😁

It does look like the built-in Monokai color scheme doesn't handle the [recommended scopes for interpolation](https://www.sublimetext.com/docs/3/scope_naming.html#string) very well — which is odd since the other built-ins (Breakers, Celeste, Mariana, Sixteen) all seem to be catching those scopes.

Although I think this is a relatively "new" standard — looks like the [RFC for interpolation scopes](https://github.com/sublimehq/Packages/issues/1875) was accepted back in February. I can update them to use the `keyword.` prefix.

**Comment by patrickrgaffney** [comment]
Regarding CI — I have access to the [GitHub actions beta](). I could take a stab at adding one of those in a later PR if you want. I played around with it on [another repo I maintain](https://github.com/patrickrgaffney/SublimeLinter-contrib-terraform/actions) and it's pretty cool, plus you don't have to leave the GH UI.

**Comment by alexlouden** [comment]
> the builtin-in JS package has gotten a lot better 

Ah, that might be it! I switched over to primarily VS Code about two years ago :)

> Regarding CI — I have access to the GitHub actions beta. I could take a stab at adding one of those in a later PR if you want. I played around with it on [another repo I maintain](https://github.com/patrickrgaffney/SublimeLinter-contrib-terraform/actions) and it's pretty cool, plus you don't have to leave the GH UI.

I had a quick poke around at creating a GH Action for it, but thought since it requires downloading and installing Sublime Text I thought maybe CircleCI's caching would help speed up tests a bit? By all means if you'd like to convert it to then go for it! The linting you set up in the other repo looks really neat

**Comment by patrickrgaffney** [comment]
Updated the scopes for the attribute-access and string interpolation operators per our previous conversation. Sorry this took so long, been a long week.

**Comment by patrickrgaffney** [comment]
@alexlouden friendly ping 🙂 Are you okay with merging this?

**Comment by alexlouden** [comment]
Oh I'm sorry I missed this, if you're happy with it then let's merge it in!

**Comment by patrickrgaffney** [comment]
Yeah, I'm good with it. I'll let you merge and cut the new release. 😎

We should probably change the `## Unreleased` in the CHANGELOG.md to the new version number (`## vX.X.X`) before the new release is made.

**Comment by jeffbyrnes** [comment]
For my own projects, I typically finalize the CHANGELOG & update the version number as a single commit, and tag that commit to use for the release.

**Comment by patrickrgaffney** [comment]
Yeah, I do something similar as well for my projects. Just didn't want to step on Alex's toes. 😁

**Comment by patrickrgaffney** [comment]
@alexlouden Did you want me to merge this?

**Comment by grigorov** [comment]
Hey, 2020 year... when merge?

**Comment by TaysirTayyab** [comment]
@alexlouden ping. Would love to get this merged in.

**Comment by plasticine** [comment]
This is amazing — thanks so much for all your work on this @patrickrgaffney & @alexlouden 👏

**Comment by alexlouden** [comment]
Sorry everyone, I've just merged it in and made a new release (hope I did it right!).

Thanks again for this @patrickrgaffney - please consider yourself a co-owner of the repo and do whatever you think is best with it going forward 😃

**Pull request merged**
